"use strict";
/**
 * Created by Paddy on 26.10.2016.
 */
exports.LANG_EN_NAME = 'en';
exports.LANG_EN_TRANS = {
    //Sidebar
    'sidebar_readXML': 'Read XML',
    'sidebar_taskPlanning': 'Task planning',
    'sidebar_task': 'Tasks',
    'sidebar_forecast': 'Forecast',
    'sidebar_productView': 'Product view',
    'sidebar_materialPlanning': 'Material planning',
    'sidebar_capacityPlanning': 'Capacity planning',
    'sidebar_prio': 'Prioritization',
    'sidebar_overview': 'Overview',
    'sidebar_history': 'History',
    'sidebar_ordersWork': 'Orders in work.',
    'sidebar_waitingWorkst': 'Waiting list workst.',
    'sidebar_warehouseStock': 'Warehouse stock',
    'sidebar_settings': 'Settings',
    'sidebar_workstations': 'Workstations',
    'sidebar_partsLists': 'Parts lists',
    'sidebar_parts': 'Parts',
    'sidebar_dashboard': 'Dashboard',
    //Headbar
    'headbar_languages': 'Languages',
    'headbar_german': 'German',
    'headbar_english': 'English',
    //CapacityPlanning
    'capacity_workstations': 'Workstations',
    'capacity_parts': 'Parts',
    'capacity_amount': 'Amount',
    'capacity_planning': 'Capacity Planning',
    'capacity_requirements': 'Capacity requirements (new)',
    'capacity_setupTime': 'Setup time (new)',
    'capacity_capacityBacklog': 'Cap. req. (backlog prev. periods)',
    'capacity_setupTimeBacklog': 'Setup time. (backlog prev. periods)',
    'capacity_totalCapacity': 'Total capacity requirements',
    'capacity_shifts': 'Shifts',
    'capacity_overtime': 'Overtimes',
    //Settings-Workstations
    'setWorkstations_workstations': 'Workstations',
    'setWorkstations_number': 'Number',
    'setWorkstations_name': 'Name',
    'setWorkstations_add': 'Add',
    'setWorkstations_reset': 'Reset',
    'setWorkstations_delete': 'Delete',
    'setWorkstations_edit': 'Edit',
    'setWorkstations_update': 'Update',
    'setWorkstations_exists': 'Workstation already exists!',
    'setWorkstations_exists_body': ' already exists.\n\nPlease choose another number',
    'setWorkstations_empty': 'Workstation incomplete!',
    'setWorkstations_empty_body': 'Number and name have to be filled.',
    //Settings-Parts
    'setParts_parts': 'Parts',
    'setParts_part': 'Part',
    'setParts_typ': 'Type',
    'setParts_number': 'Number',
    'setParts_title': 'Title',
    'setParts_worth': 'Worth',
    'setParts_stock': 'Stock',
    'setParts_usage': 'Usage',
    'setParts_components': 'Components',
    'setParts_workstations': 'Workstations',
    'setParts_workstation': 'Workstation',
    'setParts_delPeriod': 'Delivery period',
    'setParts_deviation': 'Deviation',
    'setParts_discount': 'Discount',
    'setParts_add': 'Add',
    'setParts_reset': 'Reset',
    'setParts_delete': 'Delete',
    'setParts_edit': 'Edit',
    'setParts_update': 'Update',
    'setParts_chooseComp': 'Choose components',
    'setParts_check': 'Check',
    'setParts_amount': 'Amount',
    'setParts_chooseWs': 'Choose workstations',
    'setParts_setUp': 'Set-up time',
    'setParts_procTime': 'Processing time',
    'setParts_nextWs': 'Next workstation',
    'setParts_exists': 'Part already exists!',
    'setParts_exists_body': ' already exists.\n\nPlease choose another number',
    'setParts_empty': 'Part incomplete!',
    'setParts_empty_body': 'At least one textfield is still emtpy!',
    //xmlImport
    'xmlImport': 'XML Import',
    //prediction
    'prediction_planning': 'Prediciton Planning',
    //MaterialPlanning
    'material_Planning': 'Material Planning',
    'num_purchase_part': 'Nr. Purchase Part',
    'delivery_time': 'Del.Time',
    'deviation': 'Deviation',
    'sum': 'Sum',
    'use': 'Use',
    'discount_sum': 'Discount Sum',
    'opening_stock': 'Opening Stock',
    'gross_requirements_period': 'Gross Req. Per.',
    'sum_without_order': 'Sum without order',
    'volume_ordered': 'Volume ordered',
    'ordertype': 'Order Type',
    'stock_after_receipt': 'Stock after receipt'
};
//# sourceMappingURL=lang-en.js.map